In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
#fp=r"C:\Users\shbhn\OneDrive\Desktop\spt1\GSE33000_raw_data.txt"
#df1=pd.read_table(fp, delimiter="\t", error_bad_lines=False, low_memory=False)
#df1.to_csv(r"C:\Users\shbhn\OneDrive\Desktop\spt1\GSE33000_raw_data.csv", index=None)

df1=pd.read_csv("/content/GSE33000_raw_data.csv", header=0)

In [ ]:
print(df1.columns)

Index(['reporterID', 'Gene', 'Transcript', 'HBTRC_PF_Pool_1',
       'HBTRC_PF_Pool_2', 'HBTRC_PF_Pool_3', 'HBTRC_PF_Pool_4',
       'HBTRC_PF_Pool_5', 'HBTRC_PF_Pool_6', 'HBTRC_PF_Pool_7',
       ...
       'PFC_615', 'PFC_616', 'PFC_617', 'PFC_618', 'PFC_619', 'PFC_620',
       'PFC_621', 'PFC_622', 'PFC_623', 'PFC_624'],
      dtype='object', length=1251)

In [ ]:
dfa=df1.drop(df1.columns[[0,2]], axis=1)
dfa.head()

,Gene,HBTRC_PF_Pool_1,HBTRC_PF_Pool_2,HBTRC_PF_Pool_3,HBTRC_PF_Pool_4,HBTRC_PF_Pool_5,HBTRC_PF_Pool_6,HBTRC_PF_Pool_7,HBTRC_PF_Pool_8,HBTRC_PF_Pool_9,...,PFC_615,PFC_616,PFC_617,PFC_618,PFC_619,PFC_620,PFC_621,PFC_622,PFC_623,PFC_624
0,RSE_00000118999,0.399660,0.286885,0.303855,0.259965,0.277602,0.227802,0.209805,0.203077,0.112408,...,0.9340,1.0100,1.2900,0.6390,0.494,0.6060,0.3760,0.5200,0.5760,0.6250
1,"AGRN,FLJ45064",0.295601,0.309539,0.255890,0.276044,0.224214,0.224626,0.187907,0.190715,0.211583,...,0.4590,0.5030,0.5160,0.4780,0.305,0.4240,0.3810,0.3640,0.2500,0.4170
2,"HMGB2,HMG2",0.500658,0.448259,0.462672,0.456894,0.453582,0.481320,0.473464,0.432459,0.493117,...,0.2710,0.2990,0.1820,0.3000,0.275,0.3020,1.7200,0.7030,0.3600,0.2870
3,LOC285706,0.035940,0.038750,0.041836,0.034020,0.039259,0.029540,0.030753,0.023307,0.023820,...,0.0998,0.0478,0.0412,0.0418,0.035,0.0333,0.0466,0.0324,0.0362,0.0236
4,"DNAH12,DHC3,HL19,DLP12,HL-19,hdhc3,DNAHC3,DNAHC12",0.384949,0.413481,0.359552,0.349322,0.513093,0.291822,0.465031,0.310546,0.264173,...,1.2600,0.7830,1.8800,1.6500,0.745,0.6130,0.3670,0.5280,0.5460,1.0900

In [ ]:
dfta=dfa.T
dfta.head()

,0,1,2,3,4,5,6,7,8,9,...,241,242,243,244,245,246,247,248,249,250
Gene,RSE_00000118999,"AGRN,FLJ45064","HMGB2,HMG2",LOC285706,"DNAH12,DHC3,HL19,DLP12,HL-19,hdhc3,DNAHC3,DNAHC12",DUX4,RSE_00000478328,"FLJ31033,DKFZp781D1175",RSE_00000667528,"OR2T6,OR2T9,OR2T6P,OST703",...,"CAPG,MCP,AFCP","ATP1A3,RDP,DYT12,MGC13276","PHF19,PCL3,MGC23929,MGC131698","ITLN1,LFR,HL-1,ITLN,hIntL,FLJ20022","GPRC5C,RAIG3,RAIG-3","NCOA3,ACTR,AIB1,RAC3,SRC3,pCIP,CTG26,CAGH16,TN...","AZIN1,OAZI,OAZIN,ODC1L,MGC691,MGC3832","RENT1,UPF1,HUPF1,NORF1,pNORF1,KIAA0221","KIAA0460,HSPC099,FLJ32145",HSA251708
HBTRC_PF_Pool_1,0.39966,0.295601,0.500658,0.03594,0.384949,0.229637,0.592938,0.086658,0.021768,0.09014,...,0.518053,1.428707,0.631071,0.048517,0.7944,0.64135,0.786904,0.847326,0.922263,0.75774
HBTRC_PF_Pool_2,0.286885,0.309539,0.448259,0.03875,0.413481,0.298528,0.545779,0.161326,0.014689,0.069671,...,0.47606,1.417391,0.999852,0.022478,0.826412,0.705698,0.859485,0.7208,1.222353,0.681363
HBTRC_PF_Pool_3,0.303855,0.25589,0.462672,0.041836,0.359552,0.189991,0.362186,0.155184,0.015559,0.072553,...,0.536651,1.562388,0.873184,0.027045,0.80724,0.670512,0.950756,0.793239,1.012878,0.62331
HBTRC_PF_Pool_4,0.259965,0.276044,0.456894,0.03402,0.349322,0.237163,0.391868,0.068088,0.012383,0.068583,...,0.460189,1.420336,0.885559,0.020012,0.804293,0.619657,NaN,0.779249,1.025417,0.612323

In [ ]:
np.shape(dfta)

(1249, 251)

In [ ]:
features_name=dfta.iloc[0,:-1].values
print(features_name.shape)
features_nam= np.array(features_name)

(250,)

In [ ]:
features_gene_Id=dfta.iloc[1,:-1].values
features_Id=dfta.iloc[2,:-1].values
#features= np.array(features_Id[:], dtype=int)

In [ ]:
data_set=dfta.iloc[2:,:-1].values
print ('dataset shape is ' , data_set.shape)
dataset1=np.array(data_set)

dataset shape is  (1247, 250)

In [ ]:
XX= dfta.iloc[3:,:-1].values
print ('X shape is ' , XX.shape)

X = np.array(XX)

X shape is  (1246, 250)

In [ ]:
y =dfta.iloc[3:,-1].values
print ('Y shape is ' , y.shape)
#y = np.array(y[:], dtype=int)

Y shape is  (1246,)

In [ ]:
ImputedModule = SimpleImputer(missing_values = np.nan, strategy ='mean')
ImputedX = ImputedModule.fit(X)
X = ImputedX.transform(X)